initial script commit

diff --git a/sshqc b/sshqc
--- a/sshqc
+++ b/sshqc
@@ -2,11 +2,182 @@
 CWD=$(pwd)
 echo "$CWD"
 
+# read input (cat or echo)
+read -r IN
+echo "$IN"
+
+# set globals
+KEY=
+USER_PUB_KEY=
+
 # check user is root
 ROOT_UID=0
 E_NOTROOT=87
 if [ "$UID" -ne "$ROOT_UID" ]
 then
-  echo "Must be root to run this script."
+  echo "Must be root to run."
   exit "$E_NOTROOT"
 fi
+
+# handle args
+handle_keys=false
+append_config=false
+while test $# != 0
+do
+    case "$1" in
+    -k) handle_keys=true ;;
+    -a) append_config=true ;;
+    --) shift; break;;
+    *)  usage ;;
+    esac
+    shift
+done
+
+pl_error() {
+  printf "\t[\e[31mError\e[0m] %s\n" "$1"
+}
+
+pl_success() {
+  printf "\t[\e[32mSuccess\e[0m] %s\n" "$1"
+}
+
+pl_info() {
+  printf "\t%s\n" "$1"
+}
+
+save_key() {
+  pl_info ": SAVING KEY"
+  if [ -z "$1" ]
+  then
+    pl_error "Could not get key for: $2 (Empty key file/doesn't exist)"
+  else
+    file="$HOME/.ssh/$2.key"
+    touch "$file"
+    echo "$1" >> "$file"
+    pl_success "Key saved!"
+  fi
+
+}
+
+get_key() {
+  pl_info ": GETTING KEY"
+  KEY=$(sshpass -p "$1" ssh "$2" 'cat ~/.ssh/id_rsa')
+  if [ -z "$KEY" ]
+  then
+    pl_error "Could not get key for: $2 (Empty key file/doesn't exist)"
+  else
+    pl_success "Key found!"
+  fi
+}
+
+add_authorized_key () {
+    host="$2"
+    arg_array=(${host//\@/ } )
+    user="${arg_array[0]}"
+    hostname="${arg_array[1]}"
+    pl_info ": ADDING KEY"
+
+    # create authorized keys file
+    sshpass -p "$1" ssh "$2" "touch /home/$user/.ssh/authorized_keys"
+    if [ $? -eq 0 ]
+    then
+      pl_info "Authorized keys file: GOOD"
+    else
+      pl_error "Error with creating authorized_keys on $host"
+    fi
+
+    # get authorized keys
+    authed_keys=$(sshpass -p "$1" ssh "$2" "cat /home/$user/.ssh/authorized_keys")
+    if [ -z "$authed_keys" ]
+    then
+      pl_error "Could not read authorized keys!"
+    else
+      pl_info "Reading authorized keys ..."
+    fi
+
+    # check if user's pub key in authed keys
+    if [[ "$authed_keys" == *"$USER_PUB_KEY"* ]];
+    then
+      pl_info "$SUDO_USER's key is already authorized!"
+      pl_success "Key authorized!"
+    else
+      pl_info "$SUDO_USER's key not in authorized_keys ..."
+      pl_info "adding $SUDO_USER's key to authorized_keys ..."
+      sshpass -p "$1" ssh "$2" "echo $USER_PUB_KEY >> /home/$user/.ssh/authorized_keys"
+      if [ $? -eq 0 ]
+      then
+        pl_success "Key authorized!"
+      else
+        pl_error "Error adding $SUDO_USER's key to $host"
+      fi
+    fi
+
+}
+
+get_user_pub() {
+  echo -e "======> \e[36mSTART\e[0m : local"
+  pl_info ": GETTING $SUDO_USER's PUBLIC KEY"
+  pub_dir="$HOME/.ssh/id_rsa.pub"
+  pl_info "Searching in $pub_dir ..."
+  USER_PUB_KEY=$(cat "$pub_dir")
+  if [ -z "$USER_PUB_KEY" ]
+  then
+    pl_error "Could not get $SUDO_USER's public key"
+  else
+    pl_success "Public key found!"
+  fi
+}
+
+create_config() {
+  host="$2"
+  arg_array=(${host//\@/ } )
+  config="$HOME/.ssh/config"
+  name=$1
+  user="${arg_array[0]}"
+  hostname="${arg_array[1]}"
+  pl_info ": WRITING $SUDO_USER's CONFIG FILE"
+  pl_info "config file: $config ..."
+  {
+    echo
+    echo "# $name"
+    echo "# Generated by ssh-quick-config"
+    echo "Host $name"
+    echo -e "\tUser $user"
+    echo -e "\tHostName $hostname"
+    echo -e "\tIdentityFile $HOME/.ssh/$1.key"
+    echo -e "\tPort 22"
+  } >> "$config"
+  pl_success "$1 block added!"
+}
+
+# get pub key, ssh config
+get_user_pub
+
+# main loop
+while [ "$IN" != "$entry" ] ;do
+    entry=${IN%%;*}
+    IN="${IN#$entry;}"
+    # grab credentials
+    credentials=(${entry//===/ })
+    config_name=${credentials[0]}
+    host=${credentials[1]}
+    pw=${credentials[2]}
+    # start cycle
+    echo -e "======> \e[36mSTART\e[0m : $config_name"
+    get_key "$pw" "$host" "$config_name"
+    if [ -z "$KEY" ]
+    then
+      pl_info "Skipping ... $config_name ($host)"
+    else
+      save_key "$KEY" "$config_name"
+      add_authorized_key "$pw" "$host"
+      create_config "$config_name" "$host"
+    fi
+done
+
+
+echo
+echo -e "\e[31m@@@ REMINDER: REMOVE ANY FILES WITH PASSWORD INFORMATION AFTER USE @@@"
+echo
+
+exit 0
